# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Hyde
tagline:          'My Personal Website'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              sabint54.github.io
baseurl:          /

author:
  name:           'Sabin Tandukar'
  url:            https://www.linkedin.com/in/sabin-tandukar-

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/sabint54
  repo:           https://github.com/sabint54/sabint54.github.io
