# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            'Sabin Tandukar'
tagline:          'My Personal Website'
description:      'A <a href="http://jekyllrb.com" target="_blank">graduate student</a> @Clark University majoring in Data Analytics. Also interning <a href="https://www.hologic.com/" target="_blank">@Hologic</a> as Internal Audit.'
url:              sabint54.github.io
baseurl:          /

author:
  name:           'Sabin Tandukar'
  url:            https://www.linkedin.com/in/sabin-tandukar-

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/sabint54
  repo:           
